-- AlterTable
ALTER TABLE "Reservation" ALTER COLUMN "date" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "hour" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "TrainGare" ALTER COLUMN "date" SET DEFAULT CURRENT_TIMESTAMP;
